version: "3.5"

services:
  orderbook1rn:
    container_name: orderbook1rn
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - ${PWD}/:/app/
