# Config file for GFlows.
# See https://github.com/megah4x0r/gflows/wiki/Configuration for options.
githubDir: .github
templates:
  engine: ytt
  defaults:
    dependencies:
      - https://raw.githubusercontent.com/megah4x0r/react-native-vercel-deploy-workflow-template/master
