name: "react-native-vercel-deploy"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: RN Deploy to Vercel (as web)
    environment: defaultEnv
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: read

    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Install dependencies using npm
      run: |
        npm install
      
    - name: Run npm run typescript
      run: |
        npm run typescript
        
    - name: Run npm test
      run: |
        npm test      

    - name: Convert to expo project
      run: |
        npx expoize
        
    - name: Run expo-optimize
      run: |
        npx expo-optimize
        
    - name: Run expo build for web
      run: |
        npx expo build:web

    - name: Vercel Action
      uses: amondnet/vercel-action@v20.0.0
      with:
        vercel-args: -c -C
        alias-domains: jduarter-orderbook-{{BRANCH}}
        vercel-project-name: orderbookJD
        working-directory: './web-build'
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
