name: delete-merged-branch

"on": 
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    name: Delete branch on PR close
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
